"""
Detection Data Models
=====================
Pydantic models for victim/object detection results.
In Phase 1 these are generated by the simulator;
in later phases the YOLO pipeline will populate them.
"""

from pydantic import BaseModel, Field
from datetime import datetime


class VictimDetection(BaseModel):
    """A single detected victim with geo-location and confidence."""

    id: str = Field(
        ...,
        description="Unique detection identifier",
    )
    lat: float = Field(
        ...,
        description="Latitude of the detection",
    )
    lon: float = Field(
        ...,
        description="Longitude of the detection",
    )
    confidence: float = Field(
        ...,
        description="Detection confidence score (0-1)",
        ge=0,
        le=1,
    )
    label: str = Field(
        default="person",
        description="Detection class label",
    )
    timestamp: datetime = Field(
        ...,
        description="UTC timestamp when the detection was made",
    )


class DetectionResponse(BaseModel):
    """Aggregated detection results returned by the API."""

    victims: list[VictimDetection] = Field(
        default_factory=list,
        description="List of victim detections",
    )
    total_count: int = Field(
        ...,
        description="Total number of detections",
    )
